{% set version = "9.4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-seqminer
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/seqminer_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/seqminer/seqminer_{{ version }}.tar.gz
  sha256: ac7c6dcca46e3efe3f2f49e42ddb196683b8b218ed19d446148c404670d33e55
  patches:
    - patch  # [not win]

build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - zstd
    - zlib
    - bzip2
  run:
    - r-base

test:
  requires:
    - r-testthat
  source_files:
    - tests/
  commands:
    - $R -e "library('seqminer')"                                                     # [not win]
    - $R -e "testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)"           # [not win]
    - "\"%R%\" -e \"library('seqminer')\""                                            # [win]
    - "\"%R%\" -e \"testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)\""  # [win]

about:
  home: http://seqminer.genomic.codes
  license: GPL-2.0-or-later
  summary: Integrate sequencing data (Variant call format, e.g. VCF or BCF) or meta-analysis results in R. This package can help you (1) read VCF/BCF/BGEN files by chromosomal ranges (e.g. 1:100-200); (2) read RareMETAL summary statistics files; (3) read tables from a tabix-indexed files; (4) annotate VCF/BCF files; (5)
    create customized workflow based on Makefile.
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: seqminer
# Type: Package
# Title: Efficiently Read Sequence Data (VCF Format, BCF Format, METAL Format and BGEN Format) into R
# Version: 7.1
# Date: 2019-1-7
# Authors@R: c(person("Xiaowei", "Zhan", email = "zhanxw@gmail.com", role = c("aut", "cre")), person("Dajiang", "Liu", email = "dajiang.liu@gmail.com", role = "aut"), person("Attractive Chaos", email = "attractor@live.co.uk", role = "cph", comment = "We have used the following software and made minimal necessary changes: Tabix, Heng Li <lh3@live.co.uk> (MIT license). We removed standard IO related functions, e.g. printf, fprintf ; also changed its un-safe pointer arithmetics."),	 person("Broad Institute / Massachusetts Institute of Technology", role = "cph"), person("Genome Research Ltd (GRL)", role = "cph"), person("Facebook, Inc", role = "cph"))
# Maintainer: Xiaowei Zhan <zhanxw@gmail.com>
# Description: Integrate sequencing data (Variant call format, e.g. VCF or BCF) or meta-analysis results in R. This package can help you (1) read VCF/BCF/BGEN files by chromosomal ranges (e.g. 1:100-200); (2) read RareMETAL summary statistics files; (3) read tables from a tabix-indexed files; (4) annotate VCF/BCF files; (5) create customized workflow based on Makefile.
# Copyright: We have used the following software and made minimal necessary changes: tabix, Heng Li <lh3@live.co.uk> (MIT license), SQLite (Public Domain), Zstandard (MIT license). For tabix, we removed standard IO related functions, e.g. printf, fprintf ; also changed its un-safe pointer arithmetics. For zstandard, we removed compiler (clang, MSVC) specific preprocessing flags.
# License: GPL | file LICENSE
# URL: http://seqminer.genomic.codes
# BugReports: https://github.com/zhanxw/seqminer/issues
# Packaged: 2019-01-07 21:30:23 UTC; zhanxw
# Repository: CRAN
# Suggests: testthat, SKAT
# SystemRequirements: C++11, zlib headers and libraries, GNU make, optionally also bzip2 and POSIX-compliant regex functions.
# NeedsCompilation: yes
# RoxygenNote: 6.1.1
# Encoding: UTF-8
# Author: Xiaowei Zhan [aut, cre], Dajiang Liu [aut], Attractive Chaos [cph] (We have used the following software and made minimal necessary changes: Tabix, Heng Li <lh3@live.co.uk> (MIT license). We removed standard IO related functions, e.g. printf, fprintf ; also changed its un-safe pointer arithmetics.), Broad Institute / Massachusetts Institute of Technology [cph], Genome Research Ltd (GRL) [cph], Facebook, Inc [cph]
# Date/Publication: 2019-01-08 15:20:03 UTC
