appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: g7fu+O8k8aznmfWs2gSz1czVh7S7NlJsNZ1Hb5FZRZRnpuHb4TliG+2Zr3vjIWLf1fEW8R3MzyAGcM+y319uK0XQ5+Or+z8nU/5p1pW05SyVEz2U2Lbt4XDC8tIR+zuuQ8cMGkNfJjjoviy0N91KWZZi3gu2N9qpMWf1r1C8ZaVSZLF0kW9IQi93XKqz7WTfV/Ab4rr1XKGFcXeTDtkPw3dXJYWBT3mSJQpt2blPmP6+8+mZ5qIeEIZl+ALThTtFETrfxb+ROwmCgxrO6GBE6F+/HvdvcxtaIzTOU0wJERAwIosSP0m9xZQl6W02NhL9h3yE5h065GBbiaZ8AA09floHSwr79ZXoIONEX8o96/Av0P2B4Hb7jW4j293OI8AmZSE3r/kOOhmB496qiM4P76mL2TgWVv2sWNjZoFVA/uO2JpzYyPGSMPnFiAZQ7MiTMSiShZvXX3QXg9xI2Ion34fjPBrBu2ZDgLwCPQFXkXPFzua6ssrcNKGfB8VxS9NuLYB5aTKeAWgtPx0gmWOBXvCXuhsZ9IciIftfXBTU9IKbDPNWfK4efLWWsTaO0bvVwggJAwLiosHDGLcWXM3FDxgITmq3EXekiFllOo9DnrIHaXsKIGap3xfm42FK9c9ZuqinusHCplS/VcAQPXxxv7iaLKSmm+DsajzqLZQJg0U=
conda_forge_output_validation: true
